# Generated by Django 5.2.8 on 2025-11-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shape_pt_lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('shape_pt_lon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('shape_pt_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_id', models.IntegerField()),
                ('pick_up', models.BooleanField(default=True)),
                ('drop_off', models.BooleanField(default=True)),
                ('shape_dist_traveled', models.DecimalField(decimal_places=5, max_digits=7)),
                ('timepoint', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_id', models.IntegerField()),
                ('trip_headsign', models.CharField(max_length=50)),
                ('direction_id', models.BooleanField(default=True)),
                ('shape_id', models.IntegerField()),
                ('is_accessible', models.BooleanField(default=True)),
                ('is_bikes', models.BooleanField(default=True)),
            ],
        ),
    ]
