# Generated by Django 5.2.8 on 2025-11-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ['shape_pt_sequence']},
        ),
        migrations.AlterModelOptions(
            name='stoptime',
            options={'ordering': ['stop_sequence']},
        ),
        migrations.AddField(
            model_name='stoptime',
            name='stop_sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shape',
            unique_together={('id', 'shape_pt_sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('trip_id', 'stop_sequence')},
        ),
    ]
